[2024-12-17T00:01:31.478+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: covid_data_pipeline.extract_data scheduled__2024-12-16T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-12-17T00:01:31.487+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
