[2024-12-17T00:01:32.977+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_pipeline.validate_data scheduled__2024-12-16T00:00:00+00:00 [queued]>
[2024-12-17T00:01:32.989+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_pipeline.validate_data scheduled__2024-12-16T00:00:00+00:00 [queued]>
[2024-12-17T00:01:32.989+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-17T00:01:33.005+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): validate_data> on 2024-12-16 00:00:00+00:00
[2024-12-17T00:01:33.010+0000] {standard_task_runner.py:57} INFO - Started process 2531 to run task
[2024-12-17T00:01:33.014+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_pipeline', 'validate_data', 'scheduled__2024-12-16T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/covid_pipeline_dag.py', '--cfg-path', '/tmp/tmpuky5nk52']
[2024-12-17T00:01:33.018+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask validate_data
[2024-12-17T00:01:33.096+0000] {task_command.py:416} INFO - Running <TaskInstance: covid_data_pipeline.validate_data scheduled__2024-12-16T00:00:00+00:00 [running]> on host 6c524df05549
[2024-12-17T00:01:33.209+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ctw2012105@@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_pipeline' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-16T00:00:00+00:00'
[2024-12-17T00:01:33.243+0000] {data_validator.py:34} INFO - Validating data schema
[2024-12-17T00:01:33.243+0000] {data_validator.py:50} INFO - Validating data quality
[2024-12-17T00:01:33.247+0000] {data_validator.py:82} INFO - All validations passed successfully
[2024-12-17T00:01:33.248+0000] {python.py:194} INFO - Done. Returned value was: Data validation completed
[2024-12-17T00:01:33.290+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=covid_data_pipeline, task_id=validate_data, execution_date=20241216T000000, start_date=20241217T000132, end_date=20241217T000133
[2024-12-17T00:01:33.320+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-12-17T00:01:33.355+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-17T15:47:35.598+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_pipeline.validate_data scheduled__2024-12-16T00:00:00+00:00 [queued]>
[2024-12-17T15:47:35.611+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_pipeline.validate_data scheduled__2024-12-16T00:00:00+00:00 [queued]>
[2024-12-17T15:47:35.612+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-17T15:47:35.631+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): validate_data> on 2024-12-16 00:00:00+00:00
[2024-12-17T15:47:35.637+0000] {standard_task_runner.py:57} INFO - Started process 260 to run task
[2024-12-17T15:47:35.641+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_pipeline', 'validate_data', 'scheduled__2024-12-16T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/covid_pipeline_dag.py', '--cfg-path', '/tmp/tmplo0g51ru']
[2024-12-17T15:47:35.646+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask validate_data
[2024-12-17T15:47:35.731+0000] {task_command.py:416} INFO - Running <TaskInstance: covid_data_pipeline.validate_data scheduled__2024-12-16T00:00:00+00:00 [running]> on host bee46ca94d16
[2024-12-17T15:47:35.853+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ctw2012105@@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_pipeline' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-16T00:00:00+00:00'
[2024-12-17T15:47:35.888+0000] {data_validator.py:34} INFO - Validating data schema
[2024-12-17T15:47:35.888+0000] {data_validator.py:50} INFO - Validating data quality
[2024-12-17T15:47:35.894+0000] {data_validator.py:82} INFO - All validations passed successfully
[2024-12-17T15:47:35.894+0000] {python.py:194} INFO - Done. Returned value was: Data validation completed
[2024-12-17T15:47:35.940+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=covid_data_pipeline, task_id=validate_data, execution_date=20241216T000000, start_date=20241217T154735, end_date=20241217T154735
[2024-12-17T15:47:35.986+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-12-17T15:47:36.032+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
