[2024-12-15T22:11:04.036+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_pipeline.validate_data scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T22:11:04.053+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_pipeline.validate_data scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T22:11:04.053+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-15T22:11:04.078+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): validate_data> on 2024-12-14 00:00:00+00:00
[2024-12-15T22:11:04.086+0000] {standard_task_runner.py:57} INFO - Started process 350 to run task
[2024-12-15T22:11:04.100+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_pipeline', 'validate_data', 'scheduled__2024-12-14T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/covid_pipeline_dag.py', '--cfg-path', '/tmp/tmpr18iitut']
[2024-12-15T22:11:04.106+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask validate_data
[2024-12-15T22:11:04.228+0000] {task_command.py:416} INFO - Running <TaskInstance: covid_data_pipeline.validate_data scheduled__2024-12-14T00:00:00+00:00 [running]> on host efb61c2ab0bb
[2024-12-15T22:11:04.406+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ctw2012105@@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_pipeline' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-14T00:00:00+00:00'
[2024-12-15T22:11:04.468+0000] {data_validator.py:34} INFO - Validating data schema
[2024-12-15T22:11:04.469+0000] {data_validator.py:50} INFO - Validating data quality
[2024-12-15T22:11:04.477+0000] {data_validator.py:82} INFO - All validations passed successfully
[2024-12-15T22:11:04.477+0000] {python.py:194} INFO - Done. Returned value was: Data validation completed
[2024-12-15T22:11:04.540+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=covid_data_pipeline, task_id=validate_data, execution_date=20241214T000000, start_date=20241215T221104, end_date=20241215T221104
[2024-12-15T22:11:04.602+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-12-15T22:11:04.661+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-15T23:46:26.088+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_pipeline.validate_data scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T23:46:26.108+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_pipeline.validate_data scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T23:46:26.109+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-15T23:46:26.134+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): validate_data> on 2024-12-14 00:00:00+00:00
[2024-12-15T23:46:26.141+0000] {standard_task_runner.py:57} INFO - Started process 306 to run task
[2024-12-15T23:46:26.148+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_pipeline', 'validate_data', 'scheduled__2024-12-14T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/covid_pipeline_dag.py', '--cfg-path', '/tmp/tmpi1c5msuq']
[2024-12-15T23:46:26.153+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask validate_data
[2024-12-15T23:46:26.241+0000] {task_command.py:416} INFO - Running <TaskInstance: covid_data_pipeline.validate_data scheduled__2024-12-14T00:00:00+00:00 [running]> on host 6cd16bdff3c4
[2024-12-15T23:46:26.369+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ctw2012105@@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_pipeline' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-14T00:00:00+00:00'
[2024-12-15T23:46:26.407+0000] {data_validator.py:34} INFO - Validating data schema
[2024-12-15T23:46:26.408+0000] {data_validator.py:50} INFO - Validating data quality
[2024-12-15T23:46:26.414+0000] {data_validator.py:82} INFO - All validations passed successfully
[2024-12-15T23:46:26.414+0000] {python.py:194} INFO - Done. Returned value was: Data validation completed
[2024-12-15T23:46:26.459+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=covid_data_pipeline, task_id=validate_data, execution_date=20241214T000000, start_date=20241215T234626, end_date=20241215T234626
[2024-12-15T23:46:26.492+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-12-15T23:46:26.527+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
